conda-forge/modin-feedstock

recipe/meta.yaml
Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>
Checklist
~* [ ] Reset the build number to `0` (if the version changed)~
=> Update dependency versions to match setup.py

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, README.md, build-locally.py, recipe/meta.yaml
Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>
Checklist
=> Update version to 0.8.2

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_python3.6.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.6.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.6.____cpython.yaml, .ci_support/win_64_python3.7.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .scripts/run_osx_build.sh, README.md, azure-pipelines.yml, recipe/meta.yaml
=> Add ray from conda-forge for Linux and Windows

recipe/meta.yaml, recipe/patches/0001-Remove-all-dependencies-from-setup.py.patch
#19 was only seemingly green due to https://github.com/conda-forge/status/issues/117
=> fix 0.10.2 builds

recipe/meta.yaml
Reference: https://github.com/modin-project/modin/pull/3308
Checklist
=> Pin OmniSci to pre-release for Modin 0.10.2

.github/CODEOWNERS, README.md, recipe/meta.yaml
Let's add recipe-maintainers now.
@conda-forge-admin, please rerender
=> added recipe-maintainers

recipe/meta.yaml, recipe/patches/0001-Remove-all-dependencies-from-setup.py.patch
subj. Fixed recipe for conda-forge.
=> Modin release 0.11.0

recipe/meta.yaml
Signed-off-by: Igoshev, Iaroslav <iaroslav.igoshev@intel.com>
Checklist
=> Add YarShev to maintainers

README.md
=> Add YarShev to maintainers in readme

.github/CODEOWNERS, README.md, recipe/meta.yaml
Signed-off-by: mvashishtha <mahesh@ponder.io>
Checklist
=> Make mvashishtha a maintainer.

README.md
Signed-off-by: Igoshev, Iaroslav <iaroslav.igoshev@intel.com>
Checklist
=> Replace omnisci to hdk

recipe/meta.yaml
=> Modin python 3 10

recipe/meta.yaml
Signed-off-by: izamyati <igor.zamyatin@intel.com>
Checklist
=> Allow python 3.10 for modin-hdk

recipe/meta.yaml, recipe/patches/0001-Remove-dependencies-from-env_hdk.patch, recipe/patches/0002-Remove-dependencies-from-setup.py.patch
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>
Checklist
=> changes for 0.18.0

README.md
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>
Checklist
=> update readme for Unidist

recipe/meta.yaml, recipe/patches/0001-Remove-dependencies-from-env_hdk.patch
=> updated v0.22.0

recipe/meta.yaml, recipe/patches/0001-Remove-dependencies-from-env_hdk.patch, recipe/patches/0002-Remove-dependencies-from-setup.py.patch
=> updated 0.23.0rc0

recipe/meta.yaml, recipe/patches/0001-Remove-dependencies-from-env_hdk.patch, recipe/patches/0002-Remove-dependencies-from-setup.py.patch
=> Publish Modin 0.22.3

recipe/meta.yaml, recipe/patches/0001-Remove-dependencies-from-env_hdk.patch, recipe/patches/0002-Remove-dependencies-from-setup.py.patch
=> modin v0.23.0

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-win.yml, .scripts/run_osx_build.sh, recipe/meta.yaml, recipe/patches/0001-Remove-dependencies-from-env_hdk.patch, recipe/patches/0002-Remove-dependencies-from-setup.py.patch
=> Version 0.23.1

recipe/meta.yaml
=> Rebuild Modin 0.25.0 with pin unidist <= 0.4.1

recipe/meta.yaml, recipe/patches/0002-Remove-dependencies-from-setup.py.patch
=> Release Modin 0.25.1

.azure-pipelines/azure-pipelines-win.yml, conda-forge.yml, recipe/meta.yaml
=> Use 'SET_PAGEFILE: True' option for windows

README.md, recipe/meta.yaml
=> Test builds for Modin 0.29.1

recipe/meta.yaml
=> Test builds for Modin 0.28.3

recipe/meta.yaml
=> Correct sha256

recipe/meta.yaml
=> Test builds for Modin 0.27.1

HOWTO.md, README.md, recipe/meta.yaml
=> Change modin-unidist to modin-mpi

recipe/meta.yaml
=> Pin setuptools <70.0.0 for modin-core instead of modin-ray

recipe/meta.yaml
=> Remove pin for setuptools
